### ISSUE TITLE
Algorithme de détection de fin de partie

### ISSUE THREAD

**Issue by RomainJeff** [RomainJeff/heroes-of-life#4]
Détecter quand un schema se répète ?
Détecter quand la grille est vide ?

EDIT 1 :
Détecter quand un des deux utilisateur n'a plus de cellules ?

Any ideas ?

**Comment by cytronn** [comment]
on a des contraintes au niveau des infos qu'on peut stocker?

**Comment by RomainJeff** [comment]
Non mais faut rester assez "lean" pour la qualité. :smile:

**Comment by cytronn** [comment]
Si on a un compteur de cellules dès le début, qui se met à jour à chaque refresh de la grille, on peut déjà déclarer un perdant au moment où ce compteur atteint 0.

**Comment by RomainJeff** [comment]
Donc je propose quelque chose comme ca en définitive

##### Détection d'un schema redondant (stockage des 3 dernières grilles en memoire)

``` javascript
var schemaController = function () {
    this.grilles = [];
    this.counter = 0;
};

schemaController.prototype.stock = function (grille) {
    this.counter = this.counter % 3;
    this.grilles[this.counter] = grille;

    this.counter++;
};

schemaController.prototype.hasSchema = function (grille) {
    // On verifie si la grille est egale a une des 3 precedentes grille
    // Si non on ajoute la grille aux grilles
};

```

##### Detection de fin de partie lorsqu'un des deux utilisateur n'a plus de cellules

```
On compte simplement le nombre de cellules des utilisateurs.
Ensuite on retourne "true" si l'utilisateur n'a plus de cellules sinon "false"
```

**Comment by cytronn** [comment]
j'ai pensé à ta solution, mais en allant sur cette page wikipedia : 
http://fr.wikipedia.org/wiki/Oscillateur_%28automate_cellulaire%29

On peut se rendre compte que certains oscillateurs fonctionnent sur plus de 3 étapes..

**Comment by RomainJeff** [comment]
Faut voir les probabilite mais a la rigueur on peut partir dur du 10etapes
avec le code precedent c'est juste un nombre a modif

**Comment by cytronn** [comment]
je pensais que ce serait trop chiant de stocker beaucoup d'étapes, mais dans ce cas ouais !
